name: linter
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
    -  name: install of dependency
       run: |
         pip install poetry
         make install
    -  name: linter-check
       run: |
         make lint